[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_quest_contract = "F5qfUhqkqEovEkQnxziJAVkY8spYevZU6Jd8VFCujYbJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/blackbeard/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
